# Generated by Django 3.0.8 on 2020-09-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(blank=True)),
                ('registrationNumber', models.CharField(blank=True, max_length=256)),
                ('vehicle', models.CharField(blank=True, choices=[('Byk', 'Byk'), ('Pvt', 'Pvt'), ('LGcv', 'LGcv'), ('Hgcv', 'Hgcv'), ('Lcv', 'Lcv'), ('MisD', 'MisD'), ('Dvan', 'Dvan'), ('PCV', 'PCV'), ('Rixa', 'Rixa'), ('---', '---')], max_length=256)),
                ('Type', models.CharField(choices=[('Tp', 'Tp'), ('Package', 'Package'), ('Od', 'Od'), ('---', '---')], default=('---', '---'), max_length=256)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('premiumAmount', models.FloatField(default=0)),
                ('net', models.FloatField(default=0)),
                ('tp', models.FloatField(default=0)),
                ('od', models.FloatField(default=0)),
                ('buyerPayout', models.FloatField(default=0)),
                ('sellerPayout', models.FloatField(default=0)),
                ('buyerPercantage', models.FloatField(default=0)),
                ('sellerPercantage', models.FloatField(default=0)),
                ('buyernet', models.FloatField(default=0)),
                ('sellernet', models.FloatField(default=0)),
                ('buyermode', models.CharField(choices=[('Link', 'Link'), ('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'Credit'), ('---', '---')], default=('---', '---'), max_length=256)),
                ('sellermode', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('ICICI', 'ICICI'), ('HDFC', 'HDFC'), ('YES', 'YES'), ('INDUSIND', 'INDUSIND'), ('Customer', 'Customer')], max_length=256)),
                ('buyeramount', models.FloatField(default=0)),
                ('selleramount', models.FloatField(default=0)),
                ('sellerremark', models.TextField(blank=True)),
                ('buyerremark', models.TextField(blank=True)),
                ('sellerdebit', models.FloatField(default=0)),
                ('buyerdebit', models.FloatField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policybuyer', to='insurance.Buyer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Company', to_field='company_name')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyseller', to='insurance.Seller')),
            ],
        ),
    ]
