# Generated by Django 3.1.1 on 2020-09-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20200921_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policybuyer', to='insurance.buyer'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policyseller', to='insurance.seller'),
        ),
    ]
