# Generated by Django 3.0.7 on 2020-06-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyorlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_date', models.DateField()),
                ('sourcelist', models.CharField(choices=[('AAA', 'AAA'), ('Adroit', 'Adroit'), ('Aniket', 'Aniket'), ('Milan', 'Milan'), ('Other', 'Other'), ('Valuation', 'Valuation'), ('Vijay', 'Vijay'), ('Mahindra', 'Mahindra')], max_length=10)),
                ('case_id', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True)),
                ('customer_name', models.CharField(default='NA', max_length=256)),
                ('customer_number', models.CharField(max_length=10)),
                ('alt_number', models.CharField(blank=True, default='0', max_length=10)),
                ('companylist', models.CharField(choices=[('Acko', 'Acko'), ('Auction', 'Auction'), ('AWP', 'AWP'), ('BAJAJ', 'BAJAJ'), ('Bharti', 'Bharti'), ('Car Dekho', 'Car Dekho'), ('Edelweiss', 'Edelweiss'), ('Future', 'Future'), ('GoDigit', 'GoDigit'), ('HDFC', 'HDFC'), ('Hero Fincorp', 'Hero Fincorp'), ('ICICI', 'ICICI'), ('Iffco', 'Iffco'), ('Kotak', 'Kotak'), ('Liberty', 'Liberty'), ('L&T', 'L&T'), ('Magma', 'Magma'), ('Maruti Nat', 'Maruti Nat'), ('National', 'National'), ('NewIndia', 'NewIndia'), ('Oriental', 'Oriental'), ('Rajni', 'Rajni'), ('Raheja QBE', 'Raheja QBE'), ('Reliance', 'Reliance'), ('Royal', 'Royal'), ('ShriRam', 'ShriRam'), ('TATA', 'TATA'), ('United', 'United'), ('Others', 'Others')], max_length=256)),
                ('vehicle_number', models.CharField(max_length=256)),
                ('vehicle_type', models.CharField(choices=[('BYK', 'BYK'), ('COM', 'COM'), ('PVT', 'PVT'), ('Other', 'Other')], max_length=256)),
                ('payment_type', models.CharField(choices=[('Billing', 'Billing'), ('Customer', 'Customer')], default=('Billing', 'Billing'), max_length=256)),
                ('company_cash', models.IntegerField(default=0)),
                ('case_mode', models.CharField(choices=[('Agent', 'Agent'), ('NA', 'NA'), ('Online', 'Online'), ('Surveyor', 'Surveyor')], default=('NA', 'NA'), max_length=256)),
                ('amount', models.IntegerField(default=0)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('vehicle_from', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('company_kilometer', models.IntegerField(default=0)),
                ('inspection_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Other', 'Other')], default=('Online', 'Online'), max_length=256)),
                ('surveyor_kilometer', models.IntegerField(default=0)),
                ('surveyor_cash', models.IntegerField(default=0)),
                ('cd_date', models.DateField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('remarks', models.CharField(default='NA', max_length=256)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Aprroval', 'Aprroval'), ('Assigned', 'Assigned'), ('Hold', 'Hold'), ('Done', 'Done'), ('Missing', 'Missing'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], max_length=256)),
                ('surveyorlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_register.Surveyorlist', to_field='name')),
            ],
            options={
                'ordering': ['cd_date'],
                'unique_together': {('case_id', 'companylist')},
            },
        ),
    ]
