# Generated by Django 3.0.7 on 2020-06-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['cc_date']},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set(),
        ),
    ]
