# Generated by Django 3.0.6 on 2020-06-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['cd_date']},
        ),
    ]
