# Generated by Django 3.0.7 on 2020-06-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_register', '0002_auto_20200621_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-cc_date']},
        ),
    ]
