# Generated by Django 3.0.7 on 2020-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_register', '0004_auto_20200713_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='companylist',
            field=models.CharField(choices=[('Acko', 'Acko'), ('Auction', 'Auction'), ('AWP', 'AWP'), ('BAJAJ', 'BAJAJ'), ('Bharti', 'Bharti'), ('Car Dekho', 'Car Dekho'), ('Edelweiss', 'Edelweiss'), ('Future', 'Future'), ('GoDigit', 'GoDigit'), ('HDFC', 'HDFC'), ('Hero Fincorp', 'Hero Fincorp'), ('ICICI', 'ICICI'), ('Iffco', 'Iffco'), ('Kotak', 'Kotak'), ('Liberty', 'Liberty'), ('L&T', 'L&T'), ('Magma', 'Magma'), ('Maruti Nat', 'Maruti Nat'), ('National', 'National'), ('NewIndia', 'NewIndia'), ('Oriental', 'Oriental'), ('Rajni', 'Rajni'), ('Raheja QBE', 'Raheja QBE'), ('Reliance', 'Reliance'), ('Royal', 'Royal'), ('SBI', 'SBI'), ('ShriRam', 'ShriRam'), ('Sompo', 'Sompo'), ('demo', 'demo'), ('TATA', 'TATA'), ('United', 'United'), ('Others', 'Others')], max_length=256),
        ),
    ]
